edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
fn_params_layout = "Tall"
match_block_trailing_comma = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
wrap_comments = false
